# Generated by Django 4.2.6 on 2023-11-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Whisky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=30)),
                ('aniejamiento', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('whisky', 'Whisky'), ('bourbon', 'Bourbon'), ('otros', 'Otros')], default='whisky', max_length=30)),
            ],
        ),
    ]
