# Generated by Django 4.2.6 on 2023-10-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectomoyano', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Etiqueta', models.CharField(max_length=30)),
                ('Varietal', models.CharField(max_length=30)),
                ('Cosecha', models.IntegerField()),
                ('Descripcion', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Paleta',
        ),
    ]
