# Generated by Django 4.2.6 on 2023-10-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectomoyano', '0003_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='vino',
            name='tipo',
            field=models.CharField(choices=[('vino_tinto', 'Vino Tinto'), ('vino_blanco', 'Vino Blanco'), ('vino_rosado', 'Vino Rosado')], default='vino_tinto', max_length=30),
        ),
    ]
