# Generated by Django 4.2.6 on 2023-10-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectomoyano', '0004_vino_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whisky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Etiqueta', models.CharField(max_length=30)),
                ('Aniejamiento', models.CharField(max_length=30)),
                ('Descripcion', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('whisky', 'Whisky'), ('bourbon', 'Bourbon'), ('otros', 'Otros')], default='whisky', max_length=30)),
            ],
        ),
    ]
