# Generated by Django 4.2.6 on 2023-11-09 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectomoyano', '0005_whisky'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='Consulta',
            new_name='consulta',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='Mail',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='Telefono',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='vino',
            old_name='Cosecha',
            new_name='cosecha',
        ),
        migrations.RenameField(
            model_name='vino',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='vino',
            old_name='Etiqueta',
            new_name='etiqueta',
        ),
        migrations.RenameField(
            model_name='vino',
            old_name='Varietal',
            new_name='varietal',
        ),
        migrations.RenameField(
            model_name='whisky',
            old_name='Aniejamiento',
            new_name='aniejamiento',
        ),
        migrations.RenameField(
            model_name='whisky',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='whisky',
            old_name='Etiqueta',
            new_name='etiqueta',
        ),
    ]
