# Generated by Django 4.2.6 on 2023-11-11 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectomoyano', '0008_vino_fecha_compra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Whisky',
        ),
    ]
