# Generated by Django 4.2.6 on 2023-11-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectomoyano', '0009_delete_whisky'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vino',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
