# Generated by Django 4.2.6 on 2023-11-12 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectomoyano', '0010_alter_vino_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vino',
            old_name='imagen',
            new_name='img_wine',
        ),
    ]
