# Generated by Django 4.2.6 on 2023-11-12 22:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectomoyano', '0012_rename_img_wine_vino_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vino',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
