# Generated by Django 4.2.6 on 2023-11-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lugar_residencia',
            field=models.CharField(max_length=330, null=True),
        ),
    ]
