# Generated by Django 4.2.6 on 2023-11-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='img_profile',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
